export const allScopes = [
	//dashboard
	'VIEW_OVERVIEW_PAGE',
	'EDIT_DOLLAR_VALUE',
	'VIEW_OVERVIEW_STATISTICS',

	//rental-units
	'VIEW_RENTAL_UNITS_PAGE',
	'ADD_RENTAL_UNIT',
	'VIEW_RENTAL_UNIT_DETAIL_PAGE',
	'ARCHIVE_RENTAL_UNIT',
	'EDIT_RENTAL_UNIT',
	'VIEW_UNIT_PROPERTY',
	'ADD_UNIT_PROPERTY',
	'EDIT_UNIT_PROPERTY',
	'DELETE_UNIT_PROPERTY',
	'VIEW_UNIT_AMENITIES',
	'ADD_UNIT_AMENITIES',
	'EDIT_UNIT_AMENITIES',
	'DELETE_UNIT_AMENITIES',
	'ADD_NEW_INSPECTION',

	//tenants
	'VIEW_TENANTS_PAGE',
	'VIEW_PENDING_TENANTS',
	'VIEW_TENANT_DETAIL_PAGE',
	'ADD_NEW_TENANT',
	'EDIT_TENANT',
	'DELETE_TENANT',
	'ADD_NEW_RENT',
	'APPROVE_PENDING',
	'EXTEND_RENT',
	'START_END_RENT',
	'ADD_RECEIPT',
	'EDIT_PRICE_CHANGE',
	'END_CONTRACT',
	'EDIT_RECEIPT',

	//employees
	'VIEW_EMPLOYEE_PAGE',
	'VIEW_EMPLOYEE_DETAIL_PAGE',
	'ADD_EMPLOYEE',
	'EDIT_EMPLOYEE',
	'DELETE_EMPLOYEE',
	'VIEW_ABSENT',
	'ADD_ABSENT',
	'EDIT_ABSENT',
	'VIEW_LEAVES',
	'ADD_LEAVES',
	'EDIT_LEAVES',
	'DELETE_LEAVES',
	'DELETE_ABSENT',

	//account
	'VIEW_ACCOUNT_PAGE',

	//vendor & task
	'VIEW_VENDOR_PAGE',
	'VIEW_VENDOR_DETAIL_PAGE',
	'ADD_VENDOR',
	'EDIT_VENDOR',
	'DELETE_VENDOR',
	'VIEW_VENDOR_PAYMENT',
	'ADD_PAYMENT',
	'EDIT_PAYMENT',
	'DELETE_PAYMENT',
	'VIEW_PAYMENT_DETAIL',
	'VIEW_TASK_PAGE',
	'ADD_TASK',
	'EDIT_TASK',
	'DELETE_TASK',

	//roles
	'VIEW_ROLES_PAGE',
	'ADD_ROLE',

	'DELETE_ROLE',
	'VIEW_ROLE_DETAIL_PAGE',
	'EDIT_ROLE',

	//Internal Task

	'ADD_INTERNAL_TASK',
	//can view everyone's task not just their own
	'VIEW_ALL_INTERNAL_TASK_PAGE',
	'DELETE_INTERNAL_TASK'
];
