const loreumEpisome = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`
export const unitProperty = [
	//SALON
	{
		name: 'sofa ( Futon)',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},
	{
		name: 'Chairs',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},
	{
		name: 'Side Table',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},
	{
		name: 'Coffee Table',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},
	{
		name: 'Tv Stand',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},
	{
		name: 'Tv with accessories',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},
	{
		name: 'Lamps',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},
	{
		name: 'Book Shelf',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},
	{
		name: 'Window Coverings',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},
	{
		name: 'Throw Pillows & blankets',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},
	{
		name: 'dining table with chairs',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},
	{
		name: 'bar stools',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'SALON',
	},

	//BEDROOM

	{
		name: 'Bed',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Night stand',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Table Lamp',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Dresser',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Pillow',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Pillow case',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Alarm Clock',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Hangers (cloth)',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Blinds',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'under bed box',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Blankets',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Bed spread sheet',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'mattress pad',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'window coverings',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Lamps',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'full length mirror',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'cloth organizar & shelfing',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Bed frame',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},
	{
		name: 'Box spring & mattress',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BEDROOM',
	},

	//LAUNDRY
	{
		name: 'washing machine',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'cloth basket',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'Laundry Pail',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'stain Remover',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'iron',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'ironing board',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'Drayer sheets',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'hangers',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'bleach',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'Brite White',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'bleach',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'Laundary Detergent',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'fabric softner hamper',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'drying rack',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},
	{
		name: 'sewing kit',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'LAUNDRY',
	},

	//BATHROOM

	{
		name: 'Bath Towels',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'Hand Towels',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'Shower Box',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'Toilet Brush',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'Plunger',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'Glass Cleaner',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'All Purpose Cleaner',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'Shower Organizar Or Caddy',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'Waste Basket',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'Hair Drayer',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'Wash clothes',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'Rugs',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},
	{
		name: 'Soap Dispenser',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'BATHROOM',
	},

	//KITCHEN

	{
		name: 'Blender',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'Toaster',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'Different taypes of Knife',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: '* chefs knife',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: '*partone knifes',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: '*slicing knifes',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: '*utility knifes',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: '*steak knifes',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'knife block',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'omelette pan ',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'mixing bowels',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'measuring spoons',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'muffin pans',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'cakes/ pie pans',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'piza ston / sheet',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'cookies sheet',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'pizza cutter',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'drawer organizar',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'forman grill',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'crock pot',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'can opener',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'tongs',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'veggie peeler',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'cutting board',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'wooden spoon',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'wire whisk',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'spatula ',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'fire extingusher',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'coffee maker',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'almunium foil & plastic wrap',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'caps & mags',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'dish soap',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'hand or stand mixer',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'forks',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'spoons',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'left over food storage containers',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'micro wave',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'pasta strainer',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'plates & bowels',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'pots & pans',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'pitcher',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'salt & peppers shaker',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'serving utensils',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'spice rack',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'water glasses',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'juice glasses',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'dish towels',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
	{
		name: 'oven /stove',
		description: loreumEpisome,
		numberofUnits: 1,
		propertyStatus: 'GOOD_CONDITION',
		available: true,
		itemCategory: 'KITCHEN',
	},
]
